# Generated by Django 2.2 on 2019-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200, verbose_name='access_token')),
                ('secondName', models.CharField(max_length=200, verbose_name='secondName')),
                ('firstName', models.CharField(max_length=200, verbose_name='firstName')),
                ('profilePhoto', models.URLField(max_length=400, verbose_name='profilePhoto')),
                ('ied', models.CharField(max_length=200, verbose_name='ied')),
            ],
        ),
    ]
