# Generated by Django 2.2 on 2019-04-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ied',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profilePhoto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='secondName',
        ),
    ]
