# Generated by Django 2.2 on 2019-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190424_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='geen', max_length=200, verbose_name='name'),
        ),
    ]
