# Generated by Django 2.2 on 2019-04-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190424_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='access_token',
            field=models.CharField(default='geen', max_length=200, verbose_name='access_token'),
        ),
    ]
