# Generated by Django 2.2 on 2019-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190424_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='athlete',
            field=models.CharField(default='https://www.strava.com/athletes/41206887', max_length=200, verbose_name='athlete'),
        ),
    ]
