# Generated by Django 2.2.1 on 2019-05-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='athlete',
            field=models.CharField(default='None', max_length=200, verbose_name='athlete'),
        ),
    ]
