# Generated by Django 2.2.1 on 2019-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190508_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='ied',
            field=models.IntegerField(default='0', max_length=100, verbose_name='ied'),
        ),
    ]
