# Generated by Django 2.2.1 on 2019-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_statistics_ied'),
    ]

    operations = [
        migrations.CreateModel(
            name='removeMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='geen', max_length=200, verbose_name='name')),
            ],
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ied',
            field=models.IntegerField(default='0', verbose_name='ied'),
        ),
    ]
