# Generated by Django 2.2.1 on 2019-05-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_downloads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='downloads',
            new_name='files',
        ),
    ]
