# Generated by Django 2.2.1 on 2019-05-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190520_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='files',
            new_name='mediaFiles',
        ),
    ]
