# Generated by Django 2.2.1 on 2019-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190520_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafiles',
            name='img',
            field=models.ImageField(default='None', upload_to='', verbose_name='img'),
        ),
    ]
