# Generated by Django 2.2.1 on 2019-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_mediafiles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiles',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='img'),
        ),
    ]
