# Generated by Django 2.2.1 on 2020-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190521_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='refresh_token',
            field=models.CharField(default='geen', max_length=200, verbose_name='refresh_token'),
        ),
    ]
