# Generated by Django 2.2.1 on 2020-01-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_users_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='biggest_climb_elevation_gain',
            field=models.IntegerField(default=0, null=True, verbose_name='biggest_climb_elevation_gain'),
        ),
    ]
