# Generated by Django 2.2.1 on 2020-01-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200109_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='expires_at',
            field=models.IntegerField(default='0', verbose_name='expires_at'),
        ),
    ]
