# Generated by Django 2.2.1 on 2020-01-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_users_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='recent_moving_time',
            field=models.CharField(default='00:00:00', max_length=14, verbose_name='recent_moving_time'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ytd_moving_time',
            field=models.CharField(default='00:00:00', max_length=14, verbose_name='ytd_moving_time'),
        ),
    ]
