# Generated by Django 2.2.1 on 2020-01-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200111_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='users',
            name='ytd_distance',
            field=models.IntegerField(default=0, verbose_name='distance'),
        ),
    ]
