# Generated by Django 2.2.1 on 2020-01-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200114_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='expires_at',
            field=models.IntegerField(default=1, verbose_name='expires_at'),
        ),
    ]
